### ISSUE TITLE
To Do list for updating prod

### ISSUE THREAD

**Issue by michaelmarshall** [etenlab/crowd.rocks#345]
- [x] add 13 new languages: https://github.com/etenlab/crowd.rocks/issues/339
- [x] Bring back 'Translate This Map' button when the map detail page is a translation.
- [x] update Autocomplete and Select Modal with new design https://www.figma.com/file/EESYp47j5welClXE6VGhDX/crowdrocks?node-id=336%3A4405&mode=dev 
- [x] update words and phrases apis so that having created_by and created_at fields: https://github.com/etenlab/crowd.rocks/issues/330
- [x] update filtering apis for map-list and map-translation list: https://github.com/etenlab/crowd.rocks/issues/329
- [x] add another Filter api for the map-translation list (not translated, translated, and all) sort by a-z, z-a: https://github.com/etenlab/crowd.rocks/issues/361
- [x] Map discussion bug: https://github.com/etenlab/crowd.rocks/issues/264
- [x] Ihor: i found that at the map list page https://dev.crowd.rocks/US/en/1/maps/list/en changing the language sometimes glithces. need to investigate/fix 
- [x] implement redirect to login page when get an unauthorized error: https://github.com/etenlab/crowd.rocks/issues/336
- [ ] console error after a user logs in. #379 
- [x] Elisabeth: The side menu where we login/logout/etc styling on the buttons need to be tweaked where hovering is more like a button. https://github.com/etenlab/crowd.rocks/issues/354
- [x] refactor notification, discussion and flag buttons with new design
- [x] restyle discussion title #374
- [x] bug: #347 
- [x] bug: #378 
- [x] styling in dictionary and phrase book use new UI author component #392 
- [x] bug: #397
